version: "3"

services:
  ct-webui:
    image: __ImageName__
    ports:
      - 8080:80
    deploy:
      replicas: 2
    command: /bin/bash -c "cp /usr/share/nginx/html/assets/app-settings/appsettings.__EnvironmentName__.json /usr/share/nginx/html/assets/app-settings/appsettings.json && ls | grep -P "^(?!appsettings.json$$).*" | xargs -d"\n" rm && exec nginx -g 'daemon off;'"