version: "3"

services:
  ct-webui:
    image: __ImageName__
    ports:
      - 8080:80
    deploy:
      replicas: 2
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /usr/share/nginx/html/assets/app-settings/appsettings.production.json > /usr/share/nginx/html/assets/app-settings/appsettings.json && exec nginx -g 'daemon off;'"